name: CI Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch:
        description: "The branch to deploy Coverity"
        required: true
        default: "main"
        type: string

jobs:
  preparation:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.set-branch.outputs.branch }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: recursive
          ref: ${{ inputs.branch }}

  build:
    runs-on: ubuntu-latest
    needs: preparation
    steps:
      - name: Build stage
        run: echo "Build from main branch"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Test stage
        run: echo "Test from ${{ needs.preparation.outputs.branch }} branch"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy stage
        run: echo "Deploy from ${{ needs.preparation.outputs.branch }} branch"
