name: CI Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch:
        description: "The branch to deploy Coverity"
        required: true
        default: "main"
        type: string
      checkout-ref:
        description: "Ref of the repo to checkout"
        required: true
        type: string

jobs:
  preparation:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.set-branch.outputs.branch }}
    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          ref: ${{ inputs.checkout-ref }}

      - name: Debug GitHub Ref
        run: echo "GitHub Ref: ${{ github.ref }}"

      - name: Set branch output
        id: set-branch
        run: |
          # Extract the branch name from the ref
          branch_name=$(echo "${{ github.ref }}" | sed 's#refs/heads/##')
          echo "branch=${branch_name}" >> $GITHUB_ENV
          echo "branch=${branch_name}" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: preparation
    steps:
      - name: Debug Branch Name
        run: echo "Branch from preparation: ${{ needs.preparation.outputs.branch }}"

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          ref: ${{ needs.preparation.outputs.branch }}

      - name: Build stage
        run: echo "Build from ${{ needs.preparation.outputs.branch }} branch"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Debug Branch Name
        run: echo "Branch from build: ${{ needs.build.outputs.branch }}"

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          ref: ${{ needs.build.outputs.branch }}

      - name: Test stage
        run: echo "Test from ${{ needs.build.outputs.branch }} branch"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Debug Branch Name
        run: echo "Branch from test: ${{ needs.test.outputs.branch }}"

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          ref: ${{ needs.test.outputs.branch }}

      - name: Deploy stage
        run: echo "Deploy from ${{ needs.test.outputs.branch }} branch"
