name: CI Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch:
        description: "The branch to deploy Coverity"
        required: true
        default: "main"
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Build stage
        run: echo "Build from ${{ github.event.inputs.branch }} branch"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Test stage
        run: echo "Test from ${{ github.event.inputs.branch }} branch"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Deploy stage
        run: echo "Deploy from ${{ github.event.inputs.branch }} branch"
