name: CI Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch:
        description: "The branch to deploy Coverity"
        required: true
        default: "main"
        type: string

jobs:
  preparation:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.set-branch.outputs.branch }}
    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}
      
      - name: Set branch output
        id: set-branch
        run: echo "::set-output name=branch::${{ github.event.inputs.branch }}"

  build:
    runs-on: ubuntu-latest
    needs: preparation
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.preparation.outputs.branch }}
      
      - name: Build stage
        run: echo "Build from ${{ needs.preparation.outputs.branch }} branch"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.preparation.outputs.branch }}
      
      - name: Test stage
        run: echo "Test from ${{ needs.preparation.outputs.branch }} branch"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.preparation.outputs.branch }}
      
      - name: Deploy stage
        run: echo "Deploy from ${{ needs.preparation.outputs.branch }} branch"
