name: second workflow

on:
  workflow_run:
    workflows: ["main (nightly)"]  # The name of the first workflow
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # If branch is provided as input, use it; otherwise, fallback to workflow_dispatch ref
          ref: ${{ github.event.inputs.branch || github.event.workflow_dispatch.ref }}

     
